# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
run : mkdir lol
run : cd lol
run : git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9
run : export ARCH=arm
run : export CROSS_COMPILE=../../arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
run : make cactus_defconfig O=out
run : make -j$(grep -c ^processor /proc/cpuinfo) O=out
